version: '3.9'
services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: vDm+WJ#gDT9YDp
      POSTGRES_USER: mindnet
      POSTGRES_DB: mindnet
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    image: node:20
    working_dir: /app
    command: sh -c "npm i && npm run dev"
    volumes:
      - ./api:/app
    ports:
      - "0.0.0.0:4000:4000"
    depends_on:
      - db
    env_file:
      - .env
#    environment:
#      - DATABASE_URL=${DATABASE_URL}

volumes:
  pgdata:
